name: "Validate pull request"
description: "This reusable GitHub Actions workflow provides various optional PR validations (all off by default)."

on:
  workflow_call:
    inputs:
      validate-genai-disclosure:
        description: "If true, runs the GenAI disclosure validation check on the PR body."
        required: false
        type: boolean
        default: false
      approvals-for-external-contributors:
        description: "Required number of approvers for PRs from external contributors."
        required: false
        type: number
        default: 0
      approvals-for-critical-changes:
        description: "Required number of approvers for PRs that modify many files ('critical-file-count') or critical files ('critical-files')."
        required: false
        type: number
        default: 0
      critical-file-count:
        description: "Minimum number of modified files to trigger the minimum approver requirement ('approvals-for-critical-changes')."
        required: false
        type: number
        default: 10
      critical-files:
        description: "Newline-separated list of files that, if modified, trigger the minimum approver requirement ('approvals-for-critical-changes')."
        required: false
        type: string
        default: ''

permissions:
  pull-requests: read

jobs:
  validate-genai-disclosure:
    name: "GenAI disclosure"
    if: inputs.validate-genai-disclosure
    uses: ./validate-genai-disclosure.yaml

  validate-external-contributor-approvals:
    name: "External contributor approvals"
    if: inputs.approvals-for-external-contributors > 0
    uses: ./validate-external-contributor-approvals.yaml
    with:
      approvals-for-external-contributors: ${{ inputs.approvals-for-external-contributors }}

  validate-critical-change-approvals:
    name: "Critical change approvals"
    uses: ./validate-critical-change-approvals.yaml
    with:
      approvals-for-critical-changes: ${{ inputs.approvals-for-critical-changes }}
      critical-file-count: ${{ inputs.critical-file-count }}
      critical-files: ${{ inputs.critical-files }}
